apiVersion: v1
kind: Namespace
metadata:
  name: retail-argentina
  labels:
    name: retail-argentina
    environment: production
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: retail-quota
  namespace: retail-argentina
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 8Gi
    limits.cpu: "8"
    limits.memory: 16Gi
    persistentvolumeclaims: "10"
    services: "10"
